name: iOS Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: macos-14
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Show available simulators (debug)
        run: |
          xcrun simctl list devices
          xcodebuild -list

      - name: Run tests
        run: |
          xcodebuild \
            -project Cities.xcodeproj \
            -scheme Cities \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            clean test | xcpretty && exit ${PIPESTATUS[0]}
